server:
  port: 8282

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ojtdb
    username: ojt
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: mg3XuItwtZXNbOyPdkBQ
            client-secret: GZabIF7nGD
            redirect-uri: http://localhost:8282/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response